### PR TITLE
chore: Fix codegen for fork

### PR DESCRIPTION
**Pull request by JPZ13**
This PR:
- Fixes the codegen panic. It wants the packages to be called argoproj instead of pipekit. We'd have to scrub all instances of argoproj, which we don't want to do

### CODE REVIEW

**Review by tico24 — APPROVED** [review]

**Comment by JPZ13** [comment]
This is turning out to be a nasty mess to fix given all the dependencies in codegen

**Review by isubasinghe — APPROVED** [review]

**Comment by JPZ13** [comment]
Unfortunately I can't get this to pass without undoing this commit: https://github.com/pipekit/argo-workflows/commit/0c66d4df3fc2a3fb23e7bfc73ff4bb37159f4679

@tico24 - would it be alright if we just reverted that commit and then proceeded?

**Comment by tico24** [comment]
If you revert that, we can't release.

**Comment by JPZ13** [comment]
Spoke with @tico24 today and we worked through the codegen issues

**Pull request merged**
