### PR TITLE
cherry-pick: Add container set fixes to v3.4.8 (#22)

### PR DESCRIPTION
**Pull request by JPZ13**
Cherry picks @isubasinghe's commits related to container sets against a v3.4.8 install. After validating with our affected customer, we should look to contribute these into the upstream

### CODE REVIEW

**Comment by JPZ13** [comment]
@isubasinghe - I had to make some slight changes to deal with a conflict. Could you take a look?

**Review by isubasinghe — APPROVED** [review]

**Review by Joibel — APPROVED** [review]
LGTM

**Comment by JPZ13** [comment]
@tico24 - when you're feeling better, can you cut a release of `v3.4.8-pipekit` and ping @mostaphaRoudsari when it's ready?

**Comment by mostaphaRoudsari** [comment]
Thank you, @JPZ13!

@tico24, let me know if there is anything that I can do to help with testing this.

**Pull request merged**
